export interface S_employee {
  id: number;
  emp_name: string;
  dob: string;
  mobile: string;
  email_id: string;
  profile_photo: string;
  sign_path: string;
  id_proof: string | null;
  blood_group: string;
  emp_gender: string;
  doj_rb: string;
  doj_gs: string;
  dor: string;
  perm_add: string;
  perm_district: number;
  perm_district_name: string;
  perm_state: number;
  perm_state_name: string;
  perm_pin: string;
  curr_add: string;
  curr_district: number;
  curr_district_name: string;
  curr_state: number;
  curr_state_name: string;
  curr_pin: string;
  org_id: number;
  org_desc: string;
  idCard: {
    RFID: string;
    active: number;
    card_no: string;
    valid_to: string;
    card_color: string;
    name_print: string | null;
    valid_from: string;
    id_cards_ID: number;
    cardSerialNo: string;
    card_type_id: number;
    print_desg_desc: string | null;
    police_verification_no: string | null;
  }[];
  family: {
    gender: string;
    rel_dob: string;
    eba_pass: {
      RFID: string | null;
      active: number;
      valid_to: string;
      sign_path: string | null;
      photo_path: string | null;
      valid_from: string;
      eba_card_ID: number;
      eba_card_no: string;
      id_proof_path: string | null;
    }[];
    rel_name: string;
    rel_text: string | null;
    relation: string;
    family_ID: number;
    deleted_at: string | null;
    rel_active: number;
    service_id: number;
    relation_id: number;
    service_name: string;
    rel_mobile_no: string;
  }[];
  domesticHelp: {
    dob: string;
    active: number;
    gender: string;
    mobile: string;
    eba_pass: {
      RFID: string | null;
      active: number;
      valid_to: string;
      sign_path: string | null;
      photo_path: string | null;
      valid_from: string;
      eba_card_ID: number;
      eba_card_no: string;
      id_proof_path: string | null;
    }[];
    deleted_at: string | null;
    domesticHelp_ID: number;
    domesticHelp_name: string;
    out_house_address: string;
    domesticHelpFamily: {
      gender: string;
      rel_dob: string;
      eba_pass: {
        RFID: string | null;
        active: number;
        valid_to: string;
        sign_path: string | null;
        photo_path: string | null;
        valid_from: string;
        eba_card_ID: number;
        eba_card_no: string;
        id_proof_path: string | null;
      }[];
      rel_name: string;
      relation: string;
      deleted_at: string | null;
      rel_active: number;
      relation_id: number;
      rel_mobile_no: string;
      domesticHelpfamily_ID: number;
    }[];
  }[];
  postings: {
    active: number;
    div_id: number;
    to_date: string;
    div_desc: string;
    order_no: string;
    from_date: string;
    deleted_at: string | null;
    order_date: string;
    order_path: string | null;
  }[];
  designations: {
    active: number;
    pay_id: number;
    desg_id: number;
    order_no: string;
    pay_desc: string;
    desg_desc: string;
    join_date: string;
    deleted_at: string | null;
    order_date: string;
    order_path: string | null;
  }[];
}
